name = "VectorSpin"
uuid = "bf90e979-ab1d-4d24-837a-68780c571cd7"
authors = ["Xue Hong", "Pierre Navaro"]
version = "0.2.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
<<<<<<< HEAD
DispersionRelations = "1"
=======
Aqua = "0.8"
>>>>>>> bd7a150 (Fix issues found by Aqua.jl)
DocStringExtensions = "0.9"
FFTW = "1"
LinearAlgebra = "1"
MAT = "0.10"
julia = "1"
Test = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "MAT", "Aqua"]
