name = "VectorSpin"
uuid = "bf90e979-ab1d-4d24-837a-68780c571cd7"
authors = ["Xue Hong", "Pierre Navaro"]
version = "0.2.0"

[deps]
DispersionRelations = "78f632dc-6214-4aca-89df-9f86f5ac7c9e"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
GenericFFT = "a8297547-1b15-4a5a-a998-a2ac5f1cef28"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
Aqua = "0.8"
DispersionRelations = "1"
DocStringExtensions = "0.9"
GenericFFT = "0.1.6"
LinearAlgebra = "1"
MAT = "0.10"
Test = "1"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "MAT", "Aqua"]
